
<?php
$liste = array(
array("au", "treffen"),
array("akeru", "öffnen"),
array("ageru", "geben"),
array("asobu", "spielen"),
array("arau", "waschen"),
array("aru", "da sein"),
array("aruku", "gehen"),
array("iu", "sagen"),
array("iku", "fahren"),
array("itadaku", "bekommen"),
array("iru", "da sein"),
array("uru", "verkaufen"),
array("undo suru", "sport"),
array("okiru", "aufstehen"),
array("oku", "hintun"),
array("okuru", "verschicken"),
array("okureru", "verspäten"),
array("oshieru", "lehren"),
array("ochiru", "herunterfallen"),
array("odoroku", "erschrecken"),
array("oboeru", "merken"),
array("omou", "meinen"),
array("oreru", "brechen"),
array("owaru", "enden"),
array("kau", "kaufen"),
array("kaeru", "zurückkehren"),
array("kakaru", "kosten"),
array("kaku", "schreiben"),
array("kasu", "verleihen"),
array("katadzukeru", "aufräumen"),
array("katsu", "gewinnen"),
array("kariru", "ausleihen"),
array("ganbaru", "anstrengen"),
array("kiku", "hören"),
array("kimeru", "entscheiden"),
array("kyukei suru", "pause"),
array("kiru (s)", "schneiden"),
array("kiru (t)", "tragen"),
array("kuru", "kommen"),
array("kureru", "schenken"),
array("kokai suru", "bereuen"),
array("kowareru", "kaputt gehen"),
array("sawaru", "anfassen"),
array("sanpo suru", "spazieren"),
array("shaberu", "unterhalten"),
array("shinu", "sterben"),
array("shiraberu", "untersuchen"),
array("shiru", "wissen"),
array("shinpai suru", "sorgen machen"),
array("sumu", "wohnen"),
array("suru", "machen"),
array("suwaru", "hinsetzen"),
array("soji suru", "reinigen"),
array("taberu", "essen"),
array("tamaru", "ruhig sein"),
array("chumon suru", "bestellen"),
array("tsukau", "verwenden"),
array("tsukuru", "herstellen"),
array("tsukeru", "anbringen"),
array("dekakeru", "ausgehen"),
array("dekiru", "können"),
array("deru", "raus gehen"),
array("denwa suru", "telefonieren"),
array("tobu", "springen"),
array("tomaru", "anhalten"),
array("toru (n)", "nehmen"),
array("toru (f)", "foto machen"),
array("naosu", "reparieren"),
array("nakusu", "verschwinden"),
array("naru", "werden"),
array("neru", "schlafen"),
array("nomu", "trinken"),
array("noru", "einsteigen"),
array("hairu", "reingehen"),
array("hajimeru", "anfangen"),
array("hashiru", "rennen"),
array("hataraku", "arbeiten"),
array("hanasu", "reden"),
array("harau", "bezahlen"),
array("fueru", "mehr werden"),
array("futoru", "dick werden"),
array("benkyo suru", "lernen"),
array("honyaku suru", "übersetzen"),
array("matsu", "warten"),
array("mieru", "sehen können"),
array("miseru", "zeigen"),
array("mitsukeru", "finden"),
array("miru", "sehen"),
array("musubu", "zusammen binden"),
array("motsu", "halten"),
array("motte iku", "mitnehmen"),
array("morau", "bekommen"),
array("yakusoku suru", "verabreden"),
array("yasumu", "ausruhen"),
array("yameru", "aufhören"),
array("yogoreru", "schmutzig werden"),
array("yomu", "lesen"),
array("renshu suru", "üben"),
array("wakaru", "verstehen"),
array("wasureru", "vergessen"),
array("warau", "lachen"),
array("ureshii", "glücklich"),
array("kanashii", "traurig"),
array("sabishii", "einsam"),
array("tanoshii", "angenehm"),
array("hoshii", "gewünscht sein"),
array("suki na", "gemocht sein"),
array("iya na", "unangenehm"),
array("kirai na", "nicht gemocht sein"),
array("nemui", "müde"),
array("genki na", "munter"),
array("itai", "weh tun"),
array("atatakai", "warm"),
array("atsui (h)", "heiss"),
array("samui", "kalt"),
array("tsumetai", "kalt"),
array("nurui", "lauwarm"),
array("suzushii", "kühl"),
array("mushiatsui", "schwül"),
array("oishii", "lecker"),
array("umai (l)", "lecker"),
array("mazui", "nicht lecker"),
array("amai", "süss"),
array("karai", "scharf"),
array("shiokarai", "salzig"),
array("suppai", "sauer"),
array("nigai", "bitter"),
array("asai", "flach"),
array("fukai", "tief"),
array("takai", "hoch"),
array("hikui", "niedrig"),
array("yasui", "billig"),
array("semai", "eng"),
array("hiroi", "weit"),
array("chikai", "nahe"),
array("toi", "weit entfernt"),
array("koi", "stark"),
array("usui", "dünn"),
array("atsui (d)", "dick"),
array("futoi", "dick"),
array("hosoi", "dünn"),
array("okii", "gross"),
array("chiisai", "klein"),
array("karui", "leicht"),
array("omoi", "schwer"),
array("nagai", "lang"),
array("mijikai", "kurz"),
array("marui", "rund"),
array("sukunai", "wenig"),
array("oi", "viel"),
array("aoi", "blau"),
array("akai", "rot"),
array("kiiroi", "gelb"),
array("kuroi", "schwarz"),
array("shiroi", "weiss"),
array("chairoi", "braun"),
array("haiiro no", "grau"),
array("orenji no", "orange"),
array("midori no", "grün"),
array("murasaki no", "violett"),
array("akarui", "hell"),
array("kurai", "dunkel"),
array("muzukashii", "schwierig"),
array("yasashii (le)", "leicht"),
array("kantan na", "leicht"),
array("fukuzatsu na", "kompliziert"),
array("jozu na", "geschickt"),
array("umai (g)", "geschickt"),
array("heta na", "ungeschickt"),
array("raku na", "bequem"),
array("shitsurei na", "unhöflich"),
array("teinei na", "höflich"),
array("shinsetsu na", "freundlich"),
array("yasashii (li)", "lieb"),
array("yumei na", "berühmt"),
array("binbo na", "arm"),
array("kanemochi no", "reich"),
array("benri na", "nützlich"),
array("fuben na", "unbequem"),
array("daijobu na", "in ordnung"),
array("dame na", "nutzlos"),
array("jobu na", "stabil"),
array("taihen na", "sehr schlimm"),
array("taisetsu na", "wichtig"),
array("daiji na", "wichtig"),
array("mezurashii", "selten"),
array("yoi", "gut"),
array("warui", "schlecht"),
array("sugoi", "extrem"),
array("kawaii", "süss"),
array("kitanai", "schmutzig"),
array("kirei na", "sauber"),
array("omoshiroi", "interessant"),
array("okashii", "seltsam"),
array("hen na", "komisch"),
array("tsumaranai", "langweilig"),
array("kowai", "furchterregend"),
array("abunai", "gefährlich"),
array("anzen na", "sicher"),
array("osoi", "langsam"),
array("hayai (s)", "schnell"),
array("hayai (f)", "früh"),
array("isogashii", "beschäftigt"),
array("hima na", "frei"),
array("tadashii", "richtig")
);
?>